EquipmentApp/Controllers/SaleTransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EquipmentApp.Models;

namespace EquipmentApp.Controllers
{
    public class SaleTransactionsController : Controller
    {
        private EquipmentsDBEntities db = new EquipmentsDBEntities();

        [Authorize]
        public ActionResult Success()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Customer")]
        public ActionResult AcceptOrder(int?id)
        {
            SaleTransaction saleTransaction = db.SaleTransactions.Find(id);
            saleTransaction.RequestStatus = true;
            db.Entry(saleTransaction).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("IndexForCustomer");
        }

        [HttpPost]
        [Authorize(Roles = "Customer")]
        public ActionResult RefuseOrder(int? id)
        {
            SaleTransaction saleTransaction = db.SaleTransactions.Find(id);
            saleTransaction.RequestStatus = false;
            db.Entry(saleTransaction).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("IndexForCustomer");
        }

        [HttpPost]
        [Authorize(Roles = "Customer")]
        public ActionResult SendReceipt(int? id, HttpPostedFileBase receipt)
        {
            SaleTransaction saleTransaction = db.SaleTransactions.Find(id);
            if (receipt != null)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), receipt.FileName);
                receipt.SaveAs(path);
                saleTransaction.Receipt = receipt.FileName;
            }
            db.Entry(saleTransaction).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("IndexForCustomer");
        }
        //reports for customer
        [Authorize(Roles = "Customer")]
        public ActionResult Report()
        {
            var saleTransactions = db.SaleTransactions.Include(s => s.Equipment).Include(s => s.User);
            int count1 = 0;
            int count2 = 0;
            foreach (var i in saleTransactions)
            {
                if (User.Identity.Name == i.User.UserName && i.Receipt != null)
                {
                    count1 += Convert.ToInt32(i.TotalPrice);
                }
                if (User.Identity.Name == i.Equipment.User.UserName && i.Receipt != null)
                {
                    count2 += Convert.ToInt32(i.TotalPrice);
                }
            }
            ViewData["count1"] = count1;
            ViewData["count2"] = count2;
            return View(saleTransactions.ToList());
        }

        //reports for admin
        [Authorize(Roles = "Admin")]
        public ActionResult AllReports()
        {
            var saleTransactions = db.SaleTransactions.Include(s => s.Equipment).Include(s => s.User);
                
            return View(saleTransactions.ToList());
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult AllReports(string name)
        {
            var saleTransactions = db.SaleTransactions.Include(s => s.Equipment).Include(s => s.User).Where(s=>s.User.UserName.Contains(name));
           
            return View(saleTransactions.ToList());
        }
      
        [Authorize(Roles = "Customer")]
        public ActionResult IndexForCustomer()
        {
            var saleTransactions = db.SaleTransactions.Include(s => s.Equipment).Include(s => s.User);
            return View(saleTransactions.ToList());
        }

        // GET: SaleTransactions/Details/5
        [Authorize(Roles = "Customer")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SaleTransaction saleTransaction = db.SaleTransactions.Find(id);
            if (saleTransaction == null)
            {
                return HttpNotFound();
            }
            return View(saleTransaction);
        }

        
       

        // POST: SaleTransactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        public ActionResult Create(int? id,int number)
        {
            int soldQuantity = 0;
            Equipment equipment = db.Equipments.Find(id);
            int equipmentQuantity= equipment.Quantity.Value ;
            foreach(SaleTransaction sale in db.SaleTransactions)
            {
                if (sale.Equipment_Id == id)
                {
                    soldQuantity = soldQuantity + sale.Quantity.Value;
                   
                }
            }
            if ((equipmentQuantity - soldQuantity) == 0)
            {
                TempData["message1"] = " المنتج غير متوفر !!!  جميع الكمية تم بيعها مسبقا...";
                return RedirectToAction("Details","Equipments",new { id = id });
            }
            
            else
            {
                if (((equipmentQuantity - soldQuantity)-number) < 0)
                {
                    TempData["message2"] = " الكمية المطلوبة غير متوفرة !!!";
                    return RedirectToAction("Details", "Equipments", new { id = id });
                }
                else
                {
                    SaleTransaction saleTransaction = new SaleTransaction();
                    foreach (User user in db.Users)
                    {
                        if (user.UserName == User.Identity.Name)
                        {
                            saleTransaction.User_Id = user.Id;
                        }
                    }
                    saleTransaction.Equipment_Id = id;
                    saleTransaction.TransactionDate = DateTime.Now;
                    saleTransaction.Quantity = number;
                    
                    saleTransaction.TotalPrice = number * equipment.Price;
                    saleTransaction.Receipt = null;
                    saleTransaction.RequestStatus = null;

                    db.SaleTransactions.Add(saleTransaction);
                    db.SaveChanges();
                    return RedirectToAction("Success");
                }
               
            }
            
        }
        [Authorize(Roles = "Customer")]
        public ActionResult DeleteConfirmed(int id)
        {
            SaleTransaction saleTransaction = db.SaleTransactions.Find(id);
            db.SaleTransactions.Remove(saleTransaction);
            db.SaveChanges();
            return RedirectToAction("IndexForCustomer");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EquipmentApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EquipmentApp.Models;
using System.Web.Security;
using System.IO;

namespace EquipmentApp.Controllers
{
    public class UsersController : Controller
    {
        private EquipmentsDBEntities db = new EquipmentsDBEntities();
        //profile
        [Authorize(Roles = "Customer")]
        public ActionResult Profile()
        {

            //var users = db.Users.Include(e => e.Role);
            //return View(users.ToList());
            foreach (User user in db.Users)
            {
                if (user.UserName == User.Identity.Name)
                {
                    return View(user);
                }
            }
            return RedirectToAction("Index");
        }

        //search for users

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Index(string searchtext)
        {
            var users = db.Users.Include(e => e.Role).Where(x => x.UserName.Contains(searchtext));
            return View(users.ToList());

        }

        //blocked users
        [Authorize(Roles = "Admin")]
        public ActionResult blockedUsers()
        {

            var users = db.Users.Include(u => u.Role);
            return View(users.ToList());
        }
        //home
        public ActionResult home()
        {

            return View();
        }

        //LOGIN
        public ActionResult Login()
        {
            
            return View();
        }
        [HttpPost]
       
        public ActionResult Login(int phone,string password )
        {
           
            bool isValid = db.Users.Any(x => x.PhoneNumber == phone && x.Password == password);
            if (isValid)
            {
                //foreach (User user in db.Users)
                //{
                //    if (user.UserName == username && user.Password == password && user.Block == true)
                //    {
                //        ViewData["messag"] = "خطأ!! يرجى  ";
                //        return View();
                //    }
                //}
                bool isBlock = db.Users.Any(x => x.PhoneNumber == phone && x.Password == password && x.Block == true);
                if (isBlock)
                {
                    ViewData["message1"] = " هذا الحساب محظور";
                    return View();
                }
                foreach(var i in db.Users)
                {
                    if (i.PhoneNumber == phone) {
                        FormsAuthentication.SetAuthCookie(i.UserName, false);
                        return RedirectToAction("Index", "Equipments");
                    }
                }
                
            }
            ViewData["message2"] = "خطأ!! يرجى التحقق والمحاولة مرة أخرى ";
            return View();
        }
        //Singup
        public ActionResult Singup()
        {
            //ViewBag.Role_Id = new SelectList(db.Roles, "Id", "Name");
            return View();
        }
        [HttpPost]
        
        public ActionResult Singup( string username, int phone, string password, string address, HttpPostedFileBase IDcard)
        {
                User user = new User();
                user.UserName = username;
                user.PhoneNumber = phone;
                user.Password = password;
                user.Address = address;

                user.Block = false;
                user.Role_Id = 2;
                if (IDcard != null)
                {
                    string path = Path.Combine(Server.MapPath("~/Uploads"), IDcard.FileName);
                    IDcard.SaveAs(path);
                    user.IdCard = IDcard.FileName;
                }
            bool isValidName = db.Users.Any(x => x.UserName == user.UserName);
            if (isValidName)
            {
                ViewData["message"] = "خطأ!! هذا اسم المستخدم موجود " +
                    "حاول تغير الاسم ";
                return View(user);
            }
            bool isValidPhone = db.Users.Any(x => x.PhoneNumber == user.PhoneNumber);
            if (isValidPhone)
            {
                ViewData["mes"] = "خطأ!! هذا الرقم موجود " +
                    "حاول تغير الرقم ";
                return View(user);
            }
            //foreach(var i in db.Users)
            //{
            //    if (i.UserName == user.UserName)
            //    {
            //        ViewData["message"] = "خطأ!! هذا اسم المستخدم موجود " +
            //            "حاول تغير الاسم ";
            //        return View(user);
            //    }
            //}
            db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("home");
            
                
           
        }
        //LOGOUT
        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("login");
        }

        // GET: Users
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var users = db.Users.Include(u => u.Role);
            return View(users.ToList());
        }

        // GET: Users/Details/5


        // GET: Users/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(string username, int phone, string password, string address, HttpPostedFileBase IDcard)
        {
            User user = new User();
            user.UserName = username;
            user.PhoneNumber = phone;
            user.Password = password;
            user.Address = address;

            user.Block = false;
            user.Role_Id = 2;
            if (IDcard != null)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), IDcard.FileName);
                IDcard.SaveAs(path);
                user.IdCard = IDcard.FileName;
            }
            db.Users.Add(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: Users/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            user.Block = true;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //unblock
        [Authorize(Roles = "Admin")]
        public ActionResult UnBlock(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult UnBlock(int id)
        {
            User user = db.Users.Find(id);
            user.Block = false;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EquipmentApp/Views/SaleTransactions/AllReports.cshtml
@model IEnumerable<EquipmentApp.Models.SaleTransaction>

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moadat</title>
    <link rel="icon" type="image/png" href="~/imgs/logo-tab-bar2.png">
    <!-- normalize file -->

    <link href="~/Content/normalize.css" rel="stylesheet" />
    <!-- style file -->

    <link href="~/Content/MainStyle.css" rel="stylesheet" />
    <!-- Font Awesome -->

    <link href="~/Content/all.min.css" rel="stylesheet" />
    <!-- Google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900;1000&display=swap" rel="stylesheet">
</head>
<body>
    <!-- Start Header -->
    <div class="header" id="header">
        <div class="container">
            <div class="header-left">
                <a href="#" class="logo">
                    <img src="~/imgs/logo.png" />
                </a>
                @if (User.Identity.IsAuthenticated)
                {

                    <ul>
                        <li id="megamenu-link">
                            <i class="fas fa-caret-down"></i>
                            <a href="#" target="_parent">@User.Identity.Name</a>
                            <div class="mega-menu">
                                <ul class="links">
                                    @if (!User.IsInRole("Admin"))
                                    {
                                        <li>
                                            <a href="~/Users/profile?id=@User.Identity.Name">
                                                <i class="far fa-user-circle"></i>
                                                معلوماتي
                                            </a>
                                        </li>
                                    }

                                    <li>
                                        <a href="~/Users/Logout">
                                            <i class="fas fa-sign-out-alt"></i>
                                            تسجيل الخروج
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                }

            </div>

            <ul class="main-nav">

                @if (User.Identity.IsAuthenticated)
                {


                    if (User.IsInRole("Admin"))
                    {
                        <li class="activ">@Html.ActionLink("تقارير البيع", "AllReports", "SaleTransactions")</li>
                        <li>@Html.ActionLink("تقارير الإيجار", "AllReports", "RentalRequests")</li>
                        <li>@Html.ActionLink("المسخدمين", "Index", "Users")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("طلبات البيع", "IndexForCustomer", "SaleTransactions")</li>
                        <li>@Html.ActionLink("طلبات الايجار", "IndexForCustomer", "RentalRequests")</li>
                        <li>@Html.ActionLink("عروضي", "IndexForCustomer", "Equipments")</li>
                    }



                }
                else
                {
                    <li>@Html.ActionLink("تسجيل", "Singup", "Users")</li>
                    <li>@Html.ActionLink("دخول", "Login", "Users")</li>
                }

                <li>@Html.ActionLink("الفئات", "Index", "Equipments")</li>
                <li>@Html.ActionLink("الصفحة الرئيسية", "home", "Users")</li>

            </ul>
        </div>
    </div>
    <!-- End Header -->
    <!-- Start reports-page -->
    <div class="reports-page">
        <div class="reports-box">
            <div class="top-reports">
                <div class="page-title" id="repotrt-title">
                    <i class="fas fa-chart-bar"></i>
                    <h2>تقارير البيع</h2>

                </div>
                @*<form action="AllReports" method="post" class="search-div">
            <i class="fas fa-search"></i>

            <input type="text" value="" name="name" placeholder="اسم مقدم الطلب">
            <input type="submit" value=" بحث" name="">
        </form>*@
            <form action="AllReports" method="post" class="search-div">
                <i class="fas fa-search" id="category-search"></i>
                <input type="search" value="" placeholder="اسم مقدم الطلب" name="searchtext" style="direction:rtl">
                <input type="submit" value=" بحث">
            </form>

            </div>
            <!-- تقارير صادرة -->
            <div class="reports-export" id="export">
                <table id="table-export">

                    <thead>
                        <tr>
                            <td>مالك المعدة</td>
                            <td>مقدم الطلب</td>
                            <td>اسم المنتج</td>

                            <td>نوع الطلب</td>
                            <td>تاريخ الطلب</td>

                            <td>الكمية</td>

                            <td>السعر</td>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            if (item.Receipt != null)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Equipment.User.UserName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.User.UserName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Equipment.Name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Equipment.OfferType.OfferType1)</td>

                                    <td>@Html.DisplayFor(modelItem => item.TransactionDate)</td>

                                    <td>@Html.DisplayFor(modelItem => item.Quantity)</td>

                                    <td>@Html.DisplayFor(modelItem => item.TotalPrice)</td>
                                </tr>
                            }
                        }
                    </tbody>


                </table>
            </div>

        </div>
    </div>
    <!-- End reports-page -->


</body>
</html>

EquipmentApp/Views/SaleTransactions/Details.cshtml
@model EquipmentApp.Models.SaleTransaction

@{
   
}

<!DOCTYPE html>
<html lang="en">

<body>
   
    <!-- Staer Order-Details Page -->
    <div class="order-details-page">
        <div class="dots dots-up">

        </div>
        <div class="dots dots-down">

        </div>
        <div class="details-box">
            <div class="image-order">
                <img src="~/Uploads/@Html.DisplayFor(model => model.Equipment.Image)" alt="">
            </div>
            <div class="details-content">
                <h3>تفاصيل الطلب</h3>
                <h3></h3>
                <div class="right-content">اسم المعدة :</div>
                <div class="left-content">@Html.DisplayFor(model => model.Equipment.Name)</div>

                <div class="right-content">مقدم الطلب :</div>
                <div class="left-content">
                    @Html.DisplayFor(model => model.User.UserName)
                </div>

                <div class="right-content">مالك المعدة</div>
                <div class="left-content">@Html.DisplayFor(model => model.Equipment.User.UserName)</div>

                <div class="right-content">الكمية :</div>
                <div class="left-content">@Html.DisplayFor(model => model.Quantity)</div>

                <div class="right-content">السعر الإجمالي :</div>
                <div class="left-content">@Html.DisplayFor(model => model.TotalPrice) /ر.ي</div>

                <div class="right-content">تاريخ الطلب :</div>
                <div class="left-content">@Html.DisplayFor(model => model.TransactionDate)</div>

                <div class="right-content">حالة الطلب :</div>


                @if (Model.RequestStatus == null)
                {
                    <div class="left-content">
                        لم يتم الرد
                    </div>
                }
                else
                {
                    <div class="left-content">
                        مقبول
                    </div>
                }



                <div class="right-content"> الايصال :</div>
                @if (Model.Receipt != null)
                {
                    <div class="left-content">
                        <a class="pdf-button" href="~/Uploads/@Html.DisplayFor(model => model.Receipt)" target="_blank"><i class="far fa-file-pdf"></i>فتح الملف</a>
                    </div>
                }


            </div>
        </div>
    </div>
    <!-- End Order-Details Page -->
    
    <script>
        window.onload = function () {
            document.querySelector('.header .main-nav .link-7').classList.add('activ');
        }
    </script>
</body>
</html>

EquipmentApp/Views/SaleTransactions/Report.cshtml
@model IEnumerable<EquipmentApp.Models.SaleTransaction>

@{
    
}

<!DOCTYPE html>
<html lang="en">

<body>
    
    <!-- Start reports-page -->
    <div class="reports-page">
        <div class="reports-box">
            <div class="top-reports">
                <div class="page-title" id="repotrt-title">
                    <i class="fas fa-chart-bar"></i>
                    <h2>التقارير</h2>
                </div>
                <div class="button-box button-reports">
                    <div id="btn-order"></div>
                    <button type="button" class="toggle-btn" onclick="exportbox()">الصادر</button>
                    <button type="button" class="toggle-btn" onclick="importbox()">الوارد</button>
                </div>
            </div>
            <!-- تقارير صادرة -->
            <div class="reports-export" id="export">
                <table id="table-export">
                    <caption>تقرير الطلبات الصادرة</caption>
                    <thead>
                        <tr>
                            <td>مالك المعدة</td>
                            <td>اسم المنتج</td>

                            <td>نوع الطلب</td>
                            <td>تاريخ الطلب</td>
                            
                            <td>الكمية</td>

                            <td>السعر</td>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            if (User.Identity.Name == item.User.UserName && item.Receipt != null)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Equipment.User.UserName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Equipment.Name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Equipment.OfferType.OfferType1)</td>

                                    <td>@Html.DisplayFor(modelItem => item.TransactionDate)</td>
                                   
                                    <td>@Html.DisplayFor(modelItem => item.Quantity)</td>

                                    <td>@Html.DisplayFor(modelItem => item.TotalPrice)</td>
                                </tr>
                            }
                        }
                    </tbody>

                    <tfoot>
                        <tr>
                            <td colspan="5">اجمالي المبالغ للطلبات الصادرة</td>
                            <td>@ViewData["count1"]</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- تقارير واردة -->
            <div class="reports-import" id="import" style="display: none;">
                <table id="table-export">
                    <caption>تقرير الطلبات الواردة</caption>
                    <thead>
                        <tr>
                            <td>مقدم الطلب</td>
                            <td>اسم المنتج</td>

                            <td>نوع الطلب</td>
                            <td>تاريخ الطلب</td>
                          
                            <td>الكمية</td>

                            <td>السعر</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (User.Identity.Name == item.Equipment.User.UserName && item.Receipt != null)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.User.UserName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Equipment.Name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Equipment.OfferType.OfferType1)</td>

                                    <td>@Html.DisplayFor(modelItem => item.TransactionDate)</td>
                                    
                                    <td>@Html.DisplayFor(modelItem => item.Quantity)</td>

                                    <td>@Html.DisplayFor(modelItem => item.TotalPrice)</td>
                                </tr>
                            }
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="5">اجمالي المبالغ للطلبات الواردة</td>
                            <td>@ViewData["count2"]</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <!-- End reports-page -->
   
    <script>
        var x = document.getElementById('export');
        var y = document.getElementById('import');
        var z = document.getElementById('btn-order');
        var n = document.getElementById('repotrt-title');

        function importbox() {
            // x.style.left = "-400px";
            // y.style.left = "50px";
            x.style.display = "none";
            y.style.display = "block";
            z.style.left = "144px";
            z.style.backgroundColor = "#efa840";
            n.style.color = '#efa840';
        }

        function exportbox() {
            // x.style.left = "50px";
            // y.style.left = "450px";
            x.style.display = "block";
            y.style.display = "none";
            z.style.left = "-1px";
            z.style.backgroundColor = "#2196f3";
            n.style.color = '#2196f3';
        }
        window.onload = function () {
            document.querySelector('.header .main-nav .link-7').classList.add('activ');
        }
    </script>
</body>
</html>