EquipmentApp/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Equipments = new HashSet<Equipment>();
            this.RentalRequests = new HashSet<RentalRequest>();
            this.SaleTransactions = new HashSet<SaleTransaction>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public int PhoneNumber { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public string IdCard { get; set; }
        public Nullable<bool> Block { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalRequest> RentalRequests { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleTransaction> SaleTransactions { get; set; }
    }
}

EquipmentApp/Controllers/RentalRequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EquipmentApp.Models;

namespace EquipmentApp.Controllers
{
    public class RentalRequestsController : Controller
    {
        private EquipmentsDBEntities db = new EquipmentsDBEntities();

        [Authorize]
        public ActionResult Success()
        {
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "Customer")]
        public ActionResult AcceptOrder(int? id)
        {
            RentalRequest rentalRequest = db.RentalRequests.Find(id);
            rentalRequest.RequestStatus = true;
            db.Entry(rentalRequest).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("IndexForCustomer");
        }

        [HttpPost]
        [Authorize(Roles = "Customer")]
        public ActionResult RefuseOrder(int? id)
        {
            RentalRequest rentalRequest = db.RentalRequests.Find(id);
            rentalRequest.RequestStatus = false;
            db.Entry(rentalRequest).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("IndexForCustomer");
        }

        [HttpPost]
        [Authorize(Roles = "Customer")]
        public ActionResult SendReceipt(int? id, HttpPostedFileBase receipt)
        {
            RentalRequest rentalRequest = db.RentalRequests.Find(id);
            if (receipt != null)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), receipt.FileName);
                receipt.SaveAs(path);
                rentalRequest.Receipt = receipt.FileName;
            }
            db.Entry(rentalRequest).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("IndexForCustomer");
        }

        //reports for costumer
        [Authorize(Roles = "Customer")]
        public ActionResult report()
        {
            var rentalRequests = db.RentalRequests.Include(r => r.Equipment).Include(r => r.User);
            int count1 = 0;
            int count2 = 0;
            foreach (var i in rentalRequests)
            {
                if (User.Identity.Name == i.User.UserName && i.Receipt != null)
                {
                    count1 += Convert.ToInt32(i.TotalPrice);
                }
                if (User.Identity.Name == i.Equipment.User.UserName && i.Receipt != null)
                {
                    count2 += Convert.ToInt32(i.TotalPrice);
                }
            }
            ViewData["count1"] = count1;
            ViewData["count2"] = count2;
            return View(rentalRequests.ToList());
        }
        //reports for Admin
        [Authorize(Roles = "Admin")]
        public ActionResult AllReports()
        {
            var rentalRequests = db.RentalRequests.Include(s => s.Equipment).Include(s => s.User);

            return View(rentalRequests.ToList());
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult AllReports(string name)
        {
            var rentalRequests = db.RentalRequests.Include(s => s.Equipment).Include(s => s.User).Where(s => s.User.UserName.Contains(name));

            return View(rentalRequests.ToList());
        }

        [Authorize(Roles = "Customer")]
        public ActionResult IndexForCustomer()
        {
            var rentalRequests = db.RentalRequests.Include(r => r.Equipment).Include(r => r.User);
            return View(rentalRequests.ToList());
        }
        // GET: RentalRequests/Details/5
        [Authorize(Roles = "Customer")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RentalRequest rentalRequest = db.RentalRequests.Find(id);
            if (rentalRequest == null)
            {
                return HttpNotFound();
            }
            return View(rentalRequest);
        }

       
        // POST: RentalRequests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        public ActionResult Create(int? id,DateTime startDate,DateTime endDate, int number)
        {
            int rentalQuantity = 0;
            Equipment equipment = db.Equipments.Find(id);
            int equipmentQuantity = equipment.Quantity.Value;
            foreach(RentalRequest rental in db.RentalRequests)
            {
                if (rental.Equipment_Id == id)
                {
                    if ((startDate<=rental.RentalStartDate&&endDate>=rental.RentalEndDate)||(startDate>=rental.RentalStartDate&&endDate>=rental.RentalEndDate)
                        || (startDate <= rental.RentalStartDate && endDate <= rental.RentalEndDate)|| (startDate >= rental.RentalStartDate && endDate <= rental.RentalEndDate))
                    {
                        rentalQuantity += rental.Quantity.Value;
                        
                    }
                }
            }
            if ((equipmentQuantity - rentalQuantity) == 0)
            {
                TempData["message1"] = " المنتج غير متوفر !!!  جميع الكمية مؤجره في هذا التاريخ...";
                return RedirectToAction("DetailsForRent", "Equipments", new { id = id });
            }
            else
            {
                if (((equipmentQuantity - rentalQuantity) - number) < 0)
                {
                    TempData["message2"] = " الكمية المطلوبة غير متوفرة في هذا التاريخ !!!";
                    return RedirectToAction("DetailsForRent", "Equipments", new { id = id });
                }
                else {
                    RentalRequest rentalRequest = new RentalRequest();
                    foreach (User user in db.Users)
                    {
                        if (user.UserName == User.Identity.Name)
                        {
                            rentalRequest.User_Id = user.Id;
                        }
                    }
                    rentalRequest.Equipment_Id = id;
                    rentalRequest.RequestDate = DateTime.Now;
                    rentalRequest.Quantity = number;
                    rentalRequest.RentalStartDate = startDate;
                    rentalRequest.RentalEndDate = endDate;
                    TimeSpan diff = endDate - startDate;
                    int days = (int)diff.TotalDays;
                    
                    rentalRequest.TotalPrice = number * equipment.Price * days;
                    rentalRequest.Receipt = null;
                    rentalRequest.RequestStatus = null;

                    db.RentalRequests.Add(rentalRequest);
                    db.SaveChanges();
                    return RedirectToAction("Success");
                }
            }
            
            

          
        }
        [Authorize(Roles = "Customer")]
        public ActionResult DeleteConfirmed(int id)
        {
            RentalRequest rentalRequest = db.RentalRequests.Find(id);
            db.RentalRequests.Remove(rentalRequest);
            db.SaveChanges();
            return RedirectToAction("IndexForCustomer");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EquipmentApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EquipmentApp.Models;
using System.Web.Security;
using System.IO;

namespace EquipmentApp.Controllers
{
    public class UsersController : Controller
    {
        private EquipmentsDBEntities db = new EquipmentsDBEntities();
        //profile
        [Authorize(Roles = "Customer")]
        public ActionResult Profile()
        {

            //var users = db.Users.Include(e => e.Role);
            //return View(users.ToList());
            foreach (User user in db.Users)
            {
                if (user.UserName == User.Identity.Name)
                {
                    return View(user);
                }
            }
            return RedirectToAction("Index");
        }

        //search for users

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Index(string searchtext)
        {
            var users = db.Users.Include(e => e.Role).Where(x => x.UserName.Contains(searchtext));
            return View(users.ToList());

        }

        //blocked users
        [Authorize(Roles = "Admin")]
        public ActionResult blockedUsers()
        {

            var users = db.Users.Include(u => u.Role);
            return View(users.ToList());
        }
        //home
        public ActionResult home()
        {

            return View();
        }

        //LOGIN
        public ActionResult Login()
        {
            
            return View();
        }
        [HttpPost]
       
        public ActionResult Login(int phone,string password )
        {
           
            bool isValid = db.Users.Any(x => x.PhoneNumber == phone && x.Password == password);
            if (isValid)
            {
                //foreach (User user in db.Users)
                //{
                //    if (user.UserName == username && user.Password == password && user.Block == true)
                //    {
                //        ViewData["messag"] = "خطأ!! يرجى  ";
                //        return View();
                //    }
                //}
                bool isBlock = db.Users.Any(x => x.PhoneNumber == phone && x.Password == password && x.Block == true);
                if (isBlock)
                {
                    ViewData["message1"] = " هذا الحساب محظور";
                    return View();
                }
                foreach(var i in db.Users)
                {
                    if (i.PhoneNumber == phone) {
                        FormsAuthentication.SetAuthCookie(i.UserName, false);
                        return RedirectToAction("Index", "Equipments");
                    }
                }
                
            }
            ViewData["message2"] = "خطأ!! يرجى التحقق والمحاولة مرة أخرى ";
            return View();
        }
        //Singup
        public ActionResult Singup()
        {
            //ViewBag.Role_Id = new SelectList(db.Roles, "Id", "Name");
            return View();
        }
        [HttpPost]
        
        public ActionResult Singup( string username, int phone, string password, string address, HttpPostedFileBase IDcard)
        {
                User user = new User();
                user.UserName = username;
                user.PhoneNumber = phone;
                user.Password = password;
                user.Address = address;

                user.Block = false;
                user.Role_Id = 2;
                if (IDcard != null)
                {
                    string path = Path.Combine(Server.MapPath("~/Uploads"), IDcard.FileName);
                    IDcard.SaveAs(path);
                    user.IdCard = IDcard.FileName;
                }
            bool isValidName = db.Users.Any(x => x.UserName == user.UserName);
            if (isValidName)
            {
                ViewData["message"] = "خطأ!! هذا اسم المستخدم موجود " +
                    "حاول تغير الاسم ";
                return View(user);
            }
            bool isValidPhone = db.Users.Any(x => x.PhoneNumber == user.PhoneNumber);
            if (isValidPhone)
            {
                ViewData["mes"] = "خطأ!! هذا الرقم موجود " +
                    "حاول تغير الرقم ";
                return View(user);
            }
            //foreach(var i in db.Users)
            //{
            //    if (i.UserName == user.UserName)
            //    {
            //        ViewData["message"] = "خطأ!! هذا اسم المستخدم موجود " +
            //            "حاول تغير الاسم ";
            //        return View(user);
            //    }
            //}
            db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("home");
            
                
           
        }
        //LOGOUT
        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("login");
        }

        // GET: Users
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var users = db.Users.Include(u => u.Role);
            return View(users.ToList());
        }

        // GET: Users/Details/5


        // GET: Users/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(string username, int phone, string password, string address, HttpPostedFileBase IDcard)
        {
            User user = new User();
            user.UserName = username;
            user.PhoneNumber = phone;
            user.Password = password;
            user.Address = address;

            user.Block = false;
            user.Role_Id = 2;
            if (IDcard != null)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), IDcard.FileName);
                IDcard.SaveAs(path);
                user.IdCard = IDcard.FileName;
            }
            db.Users.Add(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: Users/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            user.Block = true;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //unblock
        [Authorize(Roles = "Admin")]
        public ActionResult UnBlock(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult UnBlock(int id)
        {
            User user = db.Users.Find(id);
            user.Block = false;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EquipmentApp/Views/Users/Create.cshtml
@model EquipmentApp.Models.User

@{
    ViewBag.Title = "Create";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moadat</title>
    <link rel="icon" type="image/png" href="~/imgs/logo-tab-bar2.png">
    <!-- normalize file -->

    <link href="~/Content/normalize.css" rel="stylesheet" />
    <!-- style file -->

    <link href="~/Content/MainStyle.css" rel="stylesheet" />
    <!-- Font Awesome -->

    <link href="~/Content/all.min.css" rel="stylesheet" />
    <!-- Google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900;1000&display=swap" rel="stylesheet">
</head>
<body>
    <!-- Start Header -->
    <div class="header" id="header">
        <div class="container">
            <div class="header-left">
                <a href="#" class="logo">
                    <img src="~/imgs/logo.png" />
                </a>
                @if (User.Identity.IsAuthenticated)
                {

                    <ul>
                        <li id="megamenu-link">
                            <i class="fas fa-caret-down"></i>
                            <a href="#" target="_parent">@User.Identity.Name</a>
                            <div class="mega-menu">
                                <ul class="links">
                                    @if (!User.IsInRole("Admin"))
                                    {
                                        <li>
                                            <a href="~/Users/profile?id=@User.Identity.Name">
                                                <i class="far fa-user-circle"></i>
                                                معلوماتي
                                            </a>
                                        </li>
                                    }

                                    <li>
                                        <a href="~/Users/Logout">
                                            <i class="fas fa-sign-out-alt"></i>
                                            تسجيل الخروج
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                }

            </div>

            <ul class="main-nav">

                @if (User.Identity.IsAuthenticated)
                {


                    if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("تقارير البيع", "AllReports", "SaleTransactions")</li>
                        <li>@Html.ActionLink("تقارير الإيجار", "AllReports", "RentalRequests")</li>
                        <li class="activ">@Html.ActionLink("المسخدمين", "Index", "Users")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("طلبات البيع", "IndexForCustomer", "SaleTransactions")</li>
                        <li>@Html.ActionLink("طلبات الايجار", "IndexForCustomer", "RentalRequests")</li>
                        <li>@Html.ActionLink("عروضي", "IndexForCustomer", "Equipments")</li>
                    }



                }
                else
                {
                    <li>@Html.ActionLink("تسجيل", "Singup", "Users")</li>
                    <li>@Html.ActionLink("دخول", "Login", "Users")</li>
                }

                <li>@Html.ActionLink("الفئات", "Index", "Equipments")</li>
                <li>@Html.ActionLink("الصفحة الرئيسية", "home", "Users")</li>

            </ul>
        </div>
    </div>
    <!-- End Header -->





    <div class="signup-page">
        <div class="image">
            <img src="~//imgs/singup.png" alt="">
        </div>
        <div class="input-box">
            <p>إضافة مستخدم جديد</p>
            <form action="Singup" method="post" enctype="multipart/form-data">

                <div class="field">
                    <label for="user-name">اسم المستخدم</label>
                    <input type="text" id="user-name" name="username" value="" required>

                </div>
                <div class="field">
                    <label for="phone-id">رقم الجوال</label>
                    <input type="number" id="phone-id" name="phone" value="" required>

                </div>
                <div class="field">
                    <label for="pass-id">كلمة المرور</label>
                    <input type="password" id="password-field" name="password" required value="" pattern="^(?=.*\d)(?=.*[a-zA-Z])[\da-zA-Z]{6,}$" placeholder=" يجب ان يحتوي على الاقل 8 يشمل على الاقل حرف واحد و رقم ">
                    <i class="fas fa-eye-slash" id="password-icon" onclick="togglePasswordVisibility()"></i>
                </div>
                <div class="field">

                    <label for="select-id">العنوان</label>
                    <input type="text" id="address-id" name="address" value="" required>

                </div>
                <div class="field">
                    <label for="select-id">صورة الهوية</label>
                    <input type="file" name="IDcard" value="" required>

                </div>
                <div class="field field-submit">
                    <input type="submit" value="تسجيل ">
                </div>
                <div class="no-account">
                    <p>لديك حساب؟</p>
                    <a href="login.html">دخول</a>
                </div>
            </form>
        </div>
    </div>

    <script>
        const phoneInput = document.getElementById('phone');
        phoneInput.addEventListener('keydown', function (event) {
            if (!/[0-9]/.test(event.key) && event.key !== "Backspace") {
                event.preventDefault();
            }
        });
        function togglePasswordVisibility() {
            var passwordField = document.getElementById('password-field');
            var passwordIcon = document.getElementById('password-icon');
            if (passwordField.type === 'password') {
                passwordField.type = 'text';
                passwordIcon.classList.remove('fa-eye-slash');
                passwordIcon.classList.add('fa-eye');
            } else {
                passwordField.type = 'password';
                passwordIcon.classList.remove('fa-eye');
                passwordIcon.classList.add('fa-eye-slash');
            }
        }

    </script>
</body>




<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</html>

EquipmentApp/Views/Users/Delete.cshtml
@model EquipmentApp.Models.User

@{
    ViewBag.Title = "Delete";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moadat</title>
    <link rel="icon" type="image/png" href="~/imgs/logo-tab-bar2.png">
    @*normalize file*@

    <link href="~/Content/normalize.css" rel="stylesheet" />
    @*style file*@


<link href="~/Content/MainStyle.css" rel="stylesheet" />
    @*Font Awesome*@

    <link href="~/Content/all.min.css" rel="stylesheet" />
    @*Google font*@
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900;1000&display=swap" rel="stylesheet">
</head>
<body>
    <!-- End Header -->
    <!-- Start Header -->
    <div class="header" id="header">
        <div class="container">
            <div class="header-left">
                <a href="#" class="logo">
                    <img src="~/imgs/logo.png" />
                </a>
                @if (User.Identity.IsAuthenticated)
                {

                    <ul>
                        <li id="megamenu-link">
                            <i class="fas fa-caret-down"></i>
                            <a href="#" target="_parent">@User.Identity.Name</a>
                            <div class="mega-menu">
                                <ul class="links">
                                    @if (!User.IsInRole("Admin"))
                                    {
                                        <li>
                                            <a href="~/Users/profile?id=@User.Identity.Name">
                                                <i class="far fa-user-circle"></i>
                                                معلوماتي
                                            </a>
                                        </li>
                                    }

                                    <li>
                                        <a href="~/Users/Logout">
                                            <i class="fas fa-sign-out-alt"></i>
                                            تسجيل الخروج
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                }

            </div>

            <ul class="main-nav">

                @if (User.Identity.IsAuthenticated)
                {


                    if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("تقارير البيع", "AllReports", "SaleTransactions")</li>
                        <li>@Html.ActionLink("تقارير الإيجار", "AllReports", "RentalRequests")</li>
                        <li class="activ">@Html.ActionLink("المسخدمين", "Index", "Users")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("طلبات البيع", "IndexForCustomer", "SaleTransactions")</li>
                        <li>@Html.ActionLink("طلبات الايجار", "IndexForCustomer", "RentalRequests")</li>
                        <li>@Html.ActionLink("عروضي", "IndexForCustomer", "Equipments")</li>
                    }



                }
                else
                {
                    <li>@Html.ActionLink("تسجيل", "Singup", "Users")</li>
                    <li>@Html.ActionLink("دخول", "Login", "Users")</li>
                }

                <li>@Html.ActionLink("الفئات", "Index", "Equipments")</li>
                <li>@Html.ActionLink("الصفحة الرئيسية", "home", "Users")</li>

            </ul>
        </div>
    </div>
    <!-- End Header -->
    <!-- start confirm-block page -->
    <div class="display-block-page">
        <div class="confirm-block-box">
            <h2>حظر الحساب</h2>
            <h4>هل انت متأكد من حظر هذا الحساب؟</h4>
            <div class="user-infor">
                <h5>اسم الحساب</h5>
                <p>@Html.DisplayFor(model => model.UserName)</p>
            </div>
            <div class="user-infor">
                <h5>رقم الجوال</h5>
                <p>@Html.DisplayFor(model => model.PhoneNumber)</p>
            </div>
            <div class="user-infor">
                <h5>العنوان</h5>
                <p>@Html.DisplayFor(model => model.Address)</p>
            </div>
            <div class="confirm-buttons">
                <form action="Delete?id=@Model.Id" method="post">
                    <button type="submit">
                        <i class="far fa-check-circle"></i>
                        تاكيد الحظر
                    </button>
                </form>
                
                <button onclick="window.location.href='Index'">
                    <i class="far fa-arrow-alt-circle-left"></i>
                    العودة للخلف
                </button>
            </div>
        </div>
    </div>
    <!-- end confirm-block page -->
</body>
</html>